### ISSUE TITLE
Missing type declaration file.

### ISSUE THREAD

**Issue by homotechsual** [mrazauskas/docusaurus-remark-plugin-tab-blocks#211]
This appears to be missing it's type declaration file which causes issues in typescript Docusaurus projects.

![image](https://github.com/mrazauskas/docusaurus-remark-plugin-tab-blocks/assets/2288257/2a988730-a06f-4d48-bc72-14dcfc1de689)

**Comment by mrazauskas** [comment]
I was recently considering to add type declarations. Only that it wasn’t clear if they would be useful anyhow. Thanks for motivation to come back to the idea. Will do this soon.

**Comment by mrazauskas** [comment]
Hm.. Is there any example of a plugin with useful type declarations?

I just looked at `@docusaurus/remark-plugin-npm2yarn`. The type of the default export is `any`. Is that enough? Adding `// @ts-expect-error` would give the same `any`. That does not look convincing, but is there a better example around?

**Comment by homotechsual** [comment]
Weirdly it seems that "any" is fine - the complaint we're getting is because there's no "explicit" type definition.

Examples:
* https://github.com/remarkjs/remark-react/blob/main/index.d.ts
* https://github.com/remarkjs/remark-html/blob/main/index.d.ts

**Comment by mrazauskas** [comment]
Thanks for digging out the examples. A PR adding the `.d.ts` file is here: #212.
